### ISSUE TITLE
Traceback for tickers that are not in Quandl database

### ISSUE THREAD

**Issue by AlManja** [wbhinton/Python_Quandl#1]
When you try to download data for single ticker, if ticker is not in Quandl database, program returns traceback. Example: AG

**Comment by wbhinton** [comment]
The script is only setup to download from the SF0 database on Quandl. You would need a new database to pull from if you need other symbols.

**Comment by wbhinton** [comment]
Also, there is an issue if there is not a price in Yahoo Finance for the requested stock 365 days ago. You have to shift the days around if you get an error from a symbol you know is in the Quandl SF0 database

**Comment by AlManja** [comment]
Yes I understand that ticker is not in the database. I opened the issue for your code, to bypass the trace back. (if you want of course) Someone using your script will not know what tickers are in database. They will enter the ticker they are interested in. If ticker is not present in the database, you could have try-except loop that catches this and print our something like, "Ticker is not in database" instead that script crashes with trace back. Just a thought how to improve your code. But I can close the issue if you want

**Comment by wbhinton** [comment]
OK. I am following you now. Thanks for the advice. I will get that fixed.

**Comment by wbhinton** [comment]
Done. Thanks for the input. Its much cleaner now. 

I also fixed the date bug with another try/except statement.

**Comment by AlManja** [comment]
Great! I'm sorry I'm only pointing out but not contributing in changing the code. I'm complete noob and I'm just starting with programming and I wouldn't know how to fix and do the pull request or whatever I would need to do. Maybe in a few months. :-)
